global:
  message: Welcome to Mampe's e-commerce site 
logging:
  level:
    root: INFO
managment:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
  endpoint:
    health:
      show-details: always
