global:
  message: Welcome to dev cutomer service
message: Dev cutomer service
spring:
  application:
    name: customer-service-dev
  datasource:
    url: jdbc:mysql://localhost:3306/customer_dev
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql : true
 
